### ISSUE TITLE
script load fails

### ISSUE THREAD

**Issue by brobostigon** [zalun/mercurius-irssi#4]
when you run /script load mercurius.pl the following error comes up in irssi and the script fails to load. 

13:36 Bareword found where operator expected at ~/.irssi/scripts/mercurius.pl line 6, near ""en" class"
13:36 
13:36 I(Missing operator before class?)
13:36 
13:36 Bareword found where operator expected at ~/.irssi/scripts/mercurius.pl line 14, near "<title>mercurius"
13:36 
13:36 I(Missing operator before mercurius?)
13:36 
13:36 -!- Irssi: Error in script mercurius:
13:36 Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 689 at ~/.irssi/scripts/mercurius.pl line 14.
13:36

**Comment by mafgh** [comment]
Could you check if the file is a valid perl file? I suspect it's a html file, e.g. because of  "class" and "title".

**Comment by zalun** [comment]
Please reopen if it's still the issue
